# SimpleEmojis - Configuration
# Define your placeholder to emoji mappings here.
# Use any key like :skull: or :heart: and assign a Unicode emoji.

emojis:
  ":skull:": "â˜ " # Here, the skull with crossbones looks better in-game in my opinion.
  ":heart:": "â¤"
  ":smile:": "ğŸ˜„"
  ":fire:": "ğŸ”¥"

# You can add more mappings using /addemoji or directly here.
# If you add more mappings, remember to use /simpleemojis reload!